server:
  port: 8082

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/shopstyle-checkout
    username: postgres
    password: admin
  jpa:
    show-sql: true
    database: postgresql
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
  application:
    name: checkout
  rabbitmq:
    addresses: amqps://ucjqyuop:0uDpnIJKYbt9eCCaT8f1w5SXf6HaiZOB@jackal.rmq.cloudamqp.com/ucjqyuop
  sql:
    init:
      mode: always
      platform: postgresql

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true