server:
  port: 8082

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/shopstyle-checkout
    username: postgres
    password: admin
  jpa:
    show-sql: true
    database: postgresql
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      platform: postgresql