server:
  port: 8083

spring:
  application:
    name: history
  rabbitmq:
    addresses: amqps://ucjqyuop:0uDpnIJKYbt9eCCaT8f1w5SXf6HaiZOB@jackal.rmq.cloudamqp.com/ucjqyuop
  data:
    mongodb:
      user:
      password:
      uri: mongodb://localhost:27017/history

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
