server:
  port: 8081

spring:
  application:
    name: catalog
  data:
    mongodb:
      user:
      password:
      uri: mongodb://localhost:27017/catalog

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true