spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/shopstyle-customer
    username: postgres
    password: admin
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      platform: postgresql
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /documentation

