server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/shopstyle-customer
    username: postgres
    password: admin
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: create-drop
    aplication:
      name: customer
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      platform: postgresql

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /documentation

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

